export const data = {
    en: {
        catalog: 'catalog',
        new: 'new',
        aboutUs: 'about Us',
        checkout: 'checkout',
        check_the_entered: 'Check the entered data',
        home: 'Home',
        exchange_and_return: 'Exchange and return',
        does_not_suit: 'If your order does not suit you, we will be happy to exchange it or accept a return.',
        exchange_case: 'Exchange and return is possible in case of:',
        has_labels: 'if the order has not been used and has retained its presentation (including tags, labels, packaging materials are not violated)',
        two_days: 'return and exchange is carried out within two days from the date of receipt of the order',
        shipped_Ukraine: 'return and exchange of goods is possible only when shipped within Ukraine',
        return_form: 'a return form is included with every package',
        all_costs_exchange: 'all costs for the exchange and return of goods are borne by the buyer',
        transfer_funds: 'after receiving the return, we make a transfer of funds to the client\'s card',
        payment_delivery: "Payment and delivery",
        can_pay_methods: "You can pay for your purchase using one of the following methods:",
        nova_poshta: "cash on delivery at Nova Poshta",
        money_transfer: "money transfer Visa/MasterCard",
        privat24: "full prepayment through Privat 24",
        delivery_options: "We are ready to offer several delivery options:",
        sending_nova_poshta: "sending all over Ukraine to the branch of Nova Poshta (1-2 days)",
        international_delivery: "international delivery services for foreign residents: Ukrposhta (1-3 weeks, DHL (3-7 days)",
        delivery_time: "delivery time: 1-2 days from the date of order",
        checkout_process: "Checkout process with LIQPAY:",
        select_payment: "Select the payment method \"LIQPAY\" in the shopping cart;",
        confirm_order: "Confirm the order;",
        redirect_website: "After that, you will be redirected to the LIQPAY website, where you choose the payment method convenient for you: via Privat24, or using a Mastercard / VISA card from all over the world.",
        categories: "Categories",
        know_new: "Be the first to know about new products",
        your_email: "Your e-mail*",
        subscribe: "SUBSCRIBE",
        confidentiality: "By clicking on the \"Subscribe\" button, I agree to the processing of my personal data and have read the terms of confidentiality.",
        incorrect_email: "Incorrect E-Mail Address",
        not_entered_email: "Email address not entered",
        already_subscribed: "This email address is already subscribed",
        company: "COMPANY",
        contacts: "Contacts",
        useful: "USEFUL",
        bonus_system: "Bonus system",
        to_the_buyer: "TO THE BUYER",
        favorites: "Favorites",
        public_offer: "public offer",
        privacy_policy: "privacy Policy",
        size: "Size",
        color: "Color",
        price: "Price",
        sort_by: "Sort by",
        rising_price: "rising price",
        downward_price: "downward price",
        from: "from",
        to: "to",
        currency: "uan",
        selected: "Selected",
        goods: "goods",
        reset: "Reset",
        whole_image: "Whole image",
        complete_look: "Complete the look",
        may_like: "You may like",
        recently_viewed: "Have you recently viewed",
        select_size: "Select size",
        add_cart: "add to cart",
        to_favorites: "to favorites",
        details: "Details",
        description: "Description:",
        composition: "Composition:",
        care: "Care",
        cart: "Cart",
        your_order: "Your order",
        to_pay: "To pay",
        checkout_title: "Checkout",
        name_contain: "Name must contain at least 2 characters",
        no_name: "Name not entered",
        no_last_name: "Last name not entered",
        last_name_contain: "Last name must contain at least 2 characters",
        no_phone: "Phone not entered",
        invalid_phone: "Invalid phone number",
        no_delivery_method: "Choose a delivery method",
        no_delivery_city: "Delivery city not entered",
        no_post_office: "Post office not included",
        choose_payment: "Choose a payment method",
        enter_integer: "Enter a positive integer",
        positive_number: "Enter a positive number",
        bonus_is: "your bonus is",
        enter_number: "Enter an integer",
        personal_info: "Personal Information",
        delivery_method: "Delivery method",
        in_Ukraine: "In Ukraine",
        inter_delivery: "International delivery",
        delivery_address: "Delivery address",
        pay_method: "You can pay for your purchase using one of the following methods.",
        using_bonus: "Using the bonus account",
        write_off_bonus: "Bonus write-off amount*",
        delivery: "DELIVERY",
        bonuses: "BONUSES",
        total: "TOTAL",
        accept_terms: "By clicking on the \"pay for the order\" button, I accept the terms",
        i: "and",
        personal_area: "Personal Area",
        history_orders: "History of orders",
        personal_data: "Personal data",
        out: "Go out",
        status: "Status",
        order_price: "Order price",
        bonus_amount: "Bonus amount",
        total_amount: "Total amount",
        name_last_name: "First Name Last Name",
        phone_number: "Phone number",
        payment_method: "Payment method",
        quantity: "Quantity",
        update_info: "UPDATE INFO",
        delivery_terms: "DELIVERY TERMS",
        terms_exchange: "TERMS OF EXCHANGE AND RETURN",
        payment_information: "PAYMENT INFORMATION",
        enter_account: "Enter your personal account",
        in_processing: "In processing",
        delivered: "Delivered",
        completed: "Completed",
        canceled: "Canceled",
        password_not_entered: "Password not entered",
        password_must_contain: "Password must contain at least 8 characters",
        all_error_fields: "Fields are not filled or entered incorrectly. Please correct or re-enter.",
        go_to_login: "Have an account, login",
        registration: "Registration",
        continue: "Continue",
        enter_as_user: "Enter as user",
        registration_step_2: "Registration - step 2",
        should_receive_letter: "You should receive a letter in the mailbox",
        follow_link_proceed: "Follow the link provided to verify your email address. Then proceed to registration.",
        register: "REGISTER",
        authorization: "Authorization",
        forgot_your_password: "Forgot your password",
        not_account: "Don\'t have an account?",
        enter: "Enter",
        forgot_password: "Forgot your password",
        description_reset_password: "Enter the email address you used when registering. You will receive an email with " +
            "a link to reset your password. If you didn't receive an email, please check your email address and spam folder.",
        connect_us: "Connect with us",
        social_networks: "In social networks",
        by_phone: "By phone",
        by_mail: "By mail",
        our_office: "Our office",
        address: "Nikolaev, Krasnyh Mayovshchikov street, 13",
        enter_request: "Enter your request",
        not_request: "Request not entered",
        log_in_up: "log in / log up",
        filters: "Filters",
    },
    ua: {
        catalog: 'каталог',
        new: 'new',
        aboutUs: 'про нас',
        checkout: 'оформити замовлення',
        check_the_entered: 'Перевірте введені дані',
        home: 'головна',
        exchange_and_return: 'Обмін та повернення',
        does_not_suit: 'Якщо вам не підійшло замовлення, ми із задоволенням його обміняємо або приймемо повернення.',
        exchange_case: 'Обмін і повернення можливе у разі:',
        has_labels: 'якщо замовлення не було використане та зберегло товарний вигляд (у тому числі не порушені бирки, ярлики, пакувальні матеріали)',
        two_days: 'повернення та обмін здійснюється протягом двох днів з моменту отримання замовлення',
        shipped_Ukraine: 'повернення та обмін товару можливе лише при відправленні по Україні',
        return_form: 'бланк повернення присутній у кожній посилці',
        all_costs_exchange: 'всі витрати на обмін та повернення товару несе покупець',
        transfer_funds: 'після отримання повернення ми робимо переказ коштів на картку клієнта',
        payment_delivery: "Оплата і доставка",
        can_pay_methods: "Ви можете сплатити покупку одним з нижче перерахованих способів:",
        nova_poshta: "післяплатою у відділенні Нової Пошти",
        money_transfer: "грошовим переказом Visa/MasterCard",
        privat24: "повна передоплата через Приват 24",
        delivery_options: "Ми готові запропонувати декілька варіантів доставки:",
        sending_nova_poshta: "відправка по всій Україні до відділення Нової Пошти(1-2 дні)",
        international_delivery: "міжнародні сервіси доставки для мешканців зарубіжжя: Укрпошта( 1-3 тижні ,DHL(3-7 днів)",
        delivery_time: "термін доставки: 1-2 дні з моменту замовлення",
        checkout_process: "Процес оформлення замовлення за допомогою LIQPAY:",
        select_payment: "Вибрати у кошику спосіб оплати \"LIQPAY\";",
        confirm_order: "Підтвердити заказ;",
        redirect_website: "Після цього Вас перенаправить на сайт LIQPAY, де ви вибираєте зручний для вас спосіб оплати: через Приват24 або за допомогою картки Mastercard/VISA з усього світу.",
        categories: "Категорії",
        know_new: "Дізнайтесь першим про новинки",
        your_email: "Ваш e-mail*",
        subscribe: "ПІДПИСАТИСЯ",
        confidentiality: "Натискаючи на кнопку «Підписатися», я погоджуюсь на обробку моїх персональних даних та ознайомлений з умовами конфіденційності.",
        incorrect_email: "Неправильна адреса електронної пошти",
        not_entered_email: "Адреса електронної пошти не введена",
        already_subscribed: "Ця електронна адреса вже підписана",
        company: "КОМПАНІЯ",
        contacts: "Контакти",
        useful: "КОРИСНЕ",
        bonus_system: "Бонусна система",
        to_the_buyer: "ПОКУПЦЮ",
        favorites: "Обране",
        public_offer: "публічна оферта",
        privacy_policy: "політика конфіденційності",
        size: "Розмір",
        color: "Колір",
        price: "Ціна",
        sort_by: "Сортувати за",
        rising_price: "за зростанням ціни",
        downward_price: "по спаданню ціни",
        from: "від",
        to: "до",
        currency: "гр",
        selected: "Вибрано",
        goods: "товарів(a)",
        reset: "Скинути",
        whole_image: "Весь образ",
        complete_look: "Доповніть образ",
        may_like: "Вам може сподобатися",
        recently_viewed: "Ви нещодавно дивилися",
        select_size: "Виберіть розмір",
        add_cart: "в кошик",
        to_favorites: "у обране",
        details: "Детальніше",
        description: "Опис:",
        composition: "Склад:",
        care: "Догляд:",
        cart: "Кошик",
        your_order: "Ваше замовлення",
        to_pay: "До оплати",
        checkout_title: "Оформлення заказу",
        name_contain: "Ім'я має містити щонайменше 2 символи",
        no_name: "Ім'я не введене",
        no_last_name: "Прізвище не введено",
        last_name_contain: "Прізвище має містити щонайменше 2 символи",
        no_phone: "Телефон не введено",
        invalid_phone: "Не вірній номер телефону",
        no_delivery_method: "Виберіть спосіб доставки",
        no_delivery_city: "Місто доставки не введено",
        no_post_office: "Відділення пошти не введено",
        choose_payment: "Виберіть спосіб оплати",
        enter_integer: "Введіть позитивне ціле число",
        positive_number: "Введіть позитивне число",
        bonus_is: "ваш бонус складає",
        enter_number: "Введіть ціле число",
        personal_info: "Персональні дані",
        delivery_method: "Спосіб доставки",
        in_Ukraine: "По Україні",
        inter_delivery: "Міжнародна доставка",
        delivery_address: "Адреса доставки",
        pay_method: "Ви можете сплатити покупку одним з нижче перерахованих способів",
        using_bonus: "Використання бонусного рахунку",
        write_off_bonus: "Сума списання бонусу*",
        delivery: "ДОСТАВКА",
        bonuses: "БОНУСИ",
        total: "РАЗОМ",
        accept_terms: "Натискаючи на кнопку «сплатити замовлення», я приймаю умови",
        i: "і",
        personal_area: "Особистий кабінет",
        history_orders: "Історія замовлень",
        personal_data: "Особисті дані",
        out: "Вийти",
        status: "Статус",
        order_price: "Сума замовлення",
        bonus_amount: "Сума бонусу",
        total_amount: "Підсумкова сума",
        name_last_name: "Ім'я прізвище",
        phone_number: "Номер телефону",
        payment_method: "Спосіб оплати",
        quantity: "Кількість",
        update_info: "ОБНОВИТИ ІНФОРМАЦІЮ",
        delivery_terms: "УМОВИ ДОСТАВКИ",
        terms_exchange: "УМОВИ ОБМІНУ ТА ПОВЕРНЕННЯ",
        payment_information: "PAYMENT INFORMATION",
        enter_account: "Увійти в особистий кабінет",
        in_processing: "В обробці",
        delivered: "Доставляється",
        completed: "Виконаний",
        canceled: "Скасований",
        password_not_entered: "Пароль не введено",
        password_must_contain: "Пароль повинен містити щонайменше 8 символів",
        all_error_fields: "Поля не заповнені або введені неправильно. Виправте або введіть знову, будь ласка.",
        go_to_login: "Маєте обліковий запис, авторизуватися",
        registration: "Реєстрація",
        continue: "Продовжити",
        enter_as_user: "Увійдіть як користувач",
        registration_step_2: "Реєстрація - крок 2",
        should_receive_letter: "Вам має прийти лист на поштову скриньку",
        follow_link_proceed: "Перейдіть за цим посиланням, щоб підтвердити свою адресу електронної пошти. Потім завершіть реєстрацію.",
        register: "ЗАРЕЄСТРУВАТИСЯ",
        authorization: "Авторизація",
        forgot_your_password: "Забули пароль",
        not_account: "Немає облікового запису",
        enter: "Увійти",
        forgot_password: "Забули пароль",
        description_reset_password: "Введіть адресу електронної пошти, яку ви використовували під час реєстрації." +
            " Ви отримаєте електронного листа з посиланням на скидання пароля. Якщо ви не отримали листа, перевірте" +
            " свою адресу електронної пошти та папку зі спамом.",
        connect_us: "Зв'язатися з нами",
        social_networks: "В соціальних мережах",
        by_phone: "По телефону",
        by_mail: "Поштою",
        our_office: "Наш офіс",
        address: "м. Миколаїв, вулиця Червоних майовщиків, 13",
        enter_request: "Введіть запит",
        not_request: "Запит не введено",
        log_in_up: "увійти / реєстрація",
        filters: "Фільтри",
    },
};