export const data = {
    en: {
        catalog: 'catalog',
        new: 'new',
        aboutUs: 'about Us',
        checkout: 'checkout',
        check_the_entered: 'Check the entered data',
        home: 'Home',
        exchange_and_return: 'Exchange and return',
        does_not_suit: 'If your order does not suit you, we will be happy to exchange it or accept a return.',
        exchange_case: 'Exchange and return is possible in case of:',
        has_labels: 'if the order has not been used and has retained its presentation (including tags, labels, packaging materials are not violated)',
        two_days: 'return and exchange is carried out within two days from the date of receipt of the order',
        shipped_Ukraine: 'return and exchange of goods is possible only when shipped within Ukraine',
        return_form: 'a return form is included with every package',
        all_costs_exchange: 'all costs for the exchange and return of goods are borne by the buyer',
        transfer_funds: 'after receiving the return, we make a transfer of funds to the client\'s card',
    },
    ua: {
        catalog: 'каталог',
        new: 'new',
        aboutUs: 'о нас',
        checkout: 'оформить заказ',
        check_the_entered: 'Проверте введенные данные',
        home: 'Головна',
        exchange_and_return: 'Обмін та повернення',
        does_not_suit: 'Якщо вам не підійшло замовлення, ми із задоволенням його обміняємо або приймемо повернення.',
        exchange_case: 'Обмін і повернення можливе у разі:',
        has_labels: 'якщо замовлення не було використане та зберегло товарний вигляд (у тому числі не порушені бирки, ярлики, пакувальні матеріали)',
        two_days: 'повернення та обмін здійснюється протягом двох днів з моменту отримання замовлення',
        shipped_Ukraine: 'повернення та обмін товару можливе лише при відправленні по Україні',
        return_form: 'бланк повернення присутній у кожній посилці',
        all_costs_exchange: 'всі витрати на обмін та повернення товару несе покупець',
        transfer_funds: 'після отримання повернення ми робимо переказ коштів на картку клієнта',
    },
};